// swift-tools-version:5.3

import PackageDescription

let package = Package(
	name: "Mixpanel",
	products: [
		.library(
			name: "Mixpanel",
			targets: ["Mixpanel", "Mixpanel-ObjC"]),
	],
	dependencies: [
	],
	targets: [
		.target(
			name: "Mixpanel",
			dependencies: [],
			path: "Mixpanel",
			exclude: ["ExceptionWrapper.h", "Mixpanel.h", "ExceptionWrapper.m","Info.plist"],
			resources: [
                .process("MiniNotificationViewController.xib"),
                .process("TakeoverNotificationViewController~ipad.xib"),
                .process("TakeoverNotificationViewController~iphonelandscape.xib"),
                .process("TakeoverNotificationViewController~iphoneportrait.xib"),
                .process("MPCloseButton.png"),
                .process("MPCloseButton@2x.png"),
                .process("MPCloseButton@3x.png"),
                .process("placeholder-image.png")]
			),
        .target(name: "Mixpanel-ObjC",
                path: "Mixpanel",
                exclude: ["Constants.swift",
                          "Mixpanel.swift",
                          "Tweak.swift",
                          "BindingMessage.swift",
                          "UIImageToNSDictionary.swift",
                          "CGSizeToNSDictionary.swift",
                          "Track.swift",
                          "TweakableType.swift",
                          "InAppButton.swift",
                          "ChangeMessage.swift",
                          "TweakGroup.swift",
                          "Swizzle.swift",
                          "Decide.swift",
                          "TweakStore.swift",
                          "ReadWriteLock.swift",
                          "SHA256.swift",
                          "CGAffineTransformToNSDictionary.swift",
                          "Error.swift",
                          "UIColorToNSString.swift",
                          "TakeoverNotification.swift",
                          "ApplicationStateSerializer.swift",
                          "MixpanelType.swift",
                          "Persistence.swift",
                          "CGPointToNSDictionary.swift",
                          "MiniNotificationViewController.swift",
                          "Logger.swift",
                          "DisplayTrigger.swift",
                          "DisconnectMessage.swift",
                          "VariantAction.swift",
                          "ClearMessage.swift",
                          "MiniNotification.swift",
                          "AnyTweak.swift",
                          "UIViewSelectors.swift",
                          "UITableViewBinding.swift",
                          "ObjectIdentityProvider.swift",
                          "BaseNotificationViewController.swift",
                          "Network.swift",
                          "FileLogging.swift",
                          "Flush.swift",
                          "MD5.swift",
                          "TweakPersistency.swift",
                          "BaseWebSocketMessage.swift",
                          "MixpanelInstance.swift",
                          "ObjectSerializerConfig.swift",
                          "VariantTweak.swift",
                          "PushNotifications.swift",
                          "MixpanelNotificationServiceExtension.swift",
                          "TweakLibrary.swift",
                          "TweakBinding.swift",
                          "ObjectSerializer.swift",
                          "NSAttributedStringToNSDictionary.swift",
                          "UIEdgeInsetsToNSDictionary.swift",
                          "FlushRequest.swift",
                          "SSLSecurity.swift",
                          "DeviceInfoMessage.swift",
                          "PrintLogging.swift",
                          "Clip.swift",
                          "ObjectFilter.swift",
                          "ConnectIntegrations.swift",
                          "SessionMetadata.swift",
                          "Codeless.swift",
                          "CGRectToNSDictionary.swift",
                          "Group.swift",
                          "WebSocket.swift",
                          "People.swift",
                          "InAppNotifications.swift",
                          "UIFontToNSDictionary.swift",
                          "TweakMessage.swift",
                          "Variant.swift",
                          "UIControlBinding.swift",
                          "JSONHandler.swift",
                          "DecideRequest.swift",
                          "InAppNotification.swift",
                          "AutomaticProperties.swift",
                          "IdentityTransformer.swift",
                          "SnapshotMessage.swift",
                          "ObjectSelector.swift",
                          "TweakClusterType.swift",
                          "TakeoverNotificationViewController.swift",
                          "ABTesting.swift",
                          "AutomaticEvents.swift",
                          "TweakCollection.swift",
                          "WebSocketWrapper.swift",
                          "TweakViewData.swift",
                          "CodelessBinding.swift",
                          "SelectorEvaluator.swift",
                          "ObjectSerializerContext.swift",
                          "placeholder-image.png",
                          "MPCloseButton.png",
                          "MPCloseButton@3x.png",
                          "MPCloseButton@2x.png",
                          "placeholder-image.png",
                          "MPCloseButton.png",
                          "MPCloseButton@3x.png",
                          "MPCloseButton@2x.png"
                ]
                )
		]
)
